[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
solc = '0.8.25'
src = 'src'
test = 'test'
out = 'out'
via_ir = true
verbosity = 3
libs = [
    # ./lib are refered in toolbox-foundry/lib
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]

remappings = [
    'src/=src/',
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std/src',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

[profile.e2e]
match_path = "test/e2e/*"

[profile.unit]
block_number = 17373196
block_timestamp = 1685467379
no_match_path = "test/e2e/*"

[fuzz]
runs = 1024
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
arbitrumOne = "${RPC_ARBITRUM}"
arbitrumOneTestnet = "${RPC_ARBITRUM_SEPOLIA}"
polygon = "${RPC_POLYGON}"
scroll = "${RPC_SCROLL}"
avax = "${RPC_AVAX}"
op = "${RPC_OP}"
mantle = "${RPC_MANTLE}"
linea = "${RPC_LINEA}"
fantom = "${RPC_FANTOM}"
base = "${RPC_BASE}"
fraxtal = "${RPC_FRAXTAL}"
gnosis = "${RPC_GNOSIS}"
mode = "${RPC_MODE}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}", chain = 1, url = "https://api.etherscan.io/api/"}
sepolia = { key = "${ETHERSCAN_KEY}", chain = 11155111, url = "https://api-sepolia.etherscan.io/api/"}
arbitrumOne = { key = "${ARBISCAN_KEY}", chain = 42161, url = "https://api.arbiscan.io/api/"}
arbitrumGoerli = { key = "${ARBISCAN_KEY}", chain = 421613, url = "https://api-sepolia.arbiscan.io/api/"}
polygon = { key = "${POLYSCAN_KEY}", chain = 137, url = "https://api.polygonscan.com/api"}
scroll = { key = "${SCROLLSCAN_KEY}", chain = 534352, url = "https://api.scrollscan.com/api"}
avax = { key = "${AVAXSCAN_KEY}", chain = 43114, url = "https://api.avascan.info"}
op = { key = "${OPSCAN_KEY}",  url = "https://api-optimistic.etherscan.io/api"}
mantle = { key = "${MANTLESCAN_KEY}",  url = "https://api.mantlescan.xyz/api"}
linea = { key = "${LINEASCAN_KEY}",  url = "https://api.lineascan.build/api"}
fantom = { key = "${FANTOMSCAN_KEY}",  url = "https://api.ftmscan.com/api"}
base = { key = "${BASESCAN_KEY}",  url = "https://api.basescan.org/api"}
fraxtal = { key = "${FRAXTALSCAN_KEY}",  url = "https://api.fraxscan.com/api"}
gnosis = { key = "${GNOSISSCAN_KEY}",  url = "https://api.gnosisscan.io/api"}
mode = { key = "${MODESCAN_KEY}",  url = "https://explorer.mode.network//api"}



[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config