name: CI
on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  RPC_MAINNET: https://eth.llamarpc.com
  RPC_ARBITRUM: https://arbitrum.llamarpc.com

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm i

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run unit tests
        run: make tests
